name: myapp
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.5 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  firebase_core: 2.14.0
  get: 4.6.5
  carousel_slider: 4.2.1
  google_fonts: 5.1.0
  cloud_firestore: ^4.8.2
  hive: 2.2.3
  hive_flutter: 1.1.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/page-1/images/
  uses-material-design: true

